'use client';

import { createContext, useContext, useState } from 'react';

export type Language = 'en' | 'es' | 'fr' | 'de' | 'it' | 'pt' | 'ja' | 'ko' | 'zh' | 'ru' | 'ar' | 'hi' | 'tr' | 'vi';

const translations = {
  en: {
    sportpi: 'SPORTPI',
    tagline: 'Earn Pi, Stay Fit',
    home: 'Home',
    activities: 'Activities',
    challenges: 'Challenges',
    leaderboard: 'Leaderboard',
    profile: 'Profile',
    piBalance: 'Pi Balance',
    keepMoving: 'Keep moving to earn more',
    todaySteps: "Today's Steps",
    goal: 'Goal',
    recentActivities: 'Recent Activities',
    exerciseRewards: 'Exercise Rewards',
    walking: 'Walking',
    running: 'Running',
    cycling: 'Cycling',
    swimming: 'Swimming',
    perKm: 'per km',
    today: 'Today',
    yesterday: 'Yesterday',
    activeChallenge: 'Active Challenge',
    startActivity: 'Start Activity',
    stopActivity: 'Stop Activity',
    elapsed: 'Elapsed Time',
    distance: 'Distance',
    avgSpeed: 'Average Speed',
    elevation: 'Elevation',
    language: 'Language',
    selectLanguage: 'Select Language',
    stats: 'Stats',
    finishActivity: 'Finish Activity',
    pause: 'Pause',
    resume: 'Resume',
    currentSpeed: 'Current Speed',
    maxSpeed: 'Max Speed',
    route: 'Route',
  },
  es: {
    sportpi: 'SPORTPI',
    tagline: 'Gana Pi, Mantente en Forma',
    home: 'Inicio',
    activities: 'Actividades',
    challenges: 'Retos',
    leaderboard: 'Ranking',
    profile: 'Perfil',
    piBalance: 'Saldo de Pi',
    keepMoving: 'Sigue moviendo para ganar más',
    todaySteps: 'Pasos de Hoy',
    goal: 'Objetivo',
    recentActivities: 'Actividades Recientes',
    exerciseRewards: 'Recompensas por Ejercicio',
    walking: 'Caminar',
    running: 'Correr',
    cycling: 'Ciclismo',
    swimming: 'Natación',
    perKm: 'por km',
    today: 'Hoy',
    yesterday: 'Ayer',
    activeChallenge: 'Reto Activo',
    startActivity: 'Iniciar Actividad',
    stopActivity: 'Detener Actividad',
    elapsed: 'Tiempo Transcurrido',
    distance: 'Distancia',
    avgSpeed: 'Velocidad Promedio',
    elevation: 'Elevación',
    language: 'Idioma',
    selectLanguage: 'Seleccionar Idioma',
    stats: 'Estadísticas',
    finishActivity: 'Finalizar Actividad',
    pause: 'Pausa',
    resume: 'Reanudar',
    currentSpeed: 'Velocidad Actual',
    maxSpeed: 'Velocidad Máxima',
    route: 'Ruta',
  },
  fr: {
    sportpi: 'SPORTPI',
    tagline: 'Gagnez Pi, Restez en Forme',
    home: 'Accueil',
    activities: 'Activités',
    challenges: 'Défis',
    leaderboard: 'Classement',
    profile: 'Profil',
    piBalance: 'Solde Pi',
    keepMoving: 'Continuez à vous déplacer pour gagner plus',
    todaySteps: 'Pas Aujourd\'hui',
    goal: 'Objectif',
    recentActivities: 'Activités Récentes',
    exerciseRewards: 'Récompenses d\'Exercice',
    walking: 'Marche',
    running: 'Course',
    cycling: 'Cyclisme',
    swimming: 'Natation',
    perKm: 'par km',
    today: 'Aujourd\'hui',
    yesterday: 'Hier',
    activeChallenge: 'Défi Actif',
    startActivity: 'Démarrer l\'Activité',
    stopActivity: 'Arrêter l\'Activité',
    elapsed: 'Temps Écoulé',
    distance: 'Distance',
    avgSpeed: 'Vitesse Moyenne',
    elevation: 'Élévation',
    language: 'Langue',
    selectLanguage: 'Sélectionner la Langue',
    stats: 'Statistiques',
    finishActivity: 'Terminer l\'Activité',
    pause: 'Pause',
    resume: 'Reprendre',
    currentSpeed: 'Vitesse Actuelle',
    maxSpeed: 'Vitesse Maximale',
    route: 'Itinéraire',
  },
  de: {
    sportpi: 'SPORTPI',
    tagline: 'Verdiene Pi, Bleibe Fit',
    home: 'Startseite',
    activities: 'Aktivitäten',
    challenges: 'Herausforderungen',
    leaderboard: 'Rangliste',
    profile: 'Profil',
    piBalance: 'Pi-Guthaben',
    keepMoving: 'Bewegen Sie sich weiter, um mehr zu verdienen',
    todaySteps: 'Heutige Schritte',
    goal: 'Ziel',
    recentActivities: 'Letzte Aktivitäten',
    exerciseRewards: 'Trainingsbelohnungen',
    walking: 'Gehen',
    running: 'Laufen',
    cycling: 'Radfahren',
    swimming: 'Schwimmen',
    perKm: 'pro km',
    today: 'Heute',
    yesterday: 'Gestern',
    activeChallenge: 'Aktive Herausforderung',
    startActivity: 'Aktivität Starten',
    stopActivity: 'Aktivität Beenden',
    elapsed: 'Verstrichene Zeit',
    distance: 'Distanz',
    avgSpeed: 'Durchschnittliche Geschwindigkeit',
    elevation: 'Höhe',
    language: 'Sprache',
    selectLanguage: 'Sprache Wählen',
    stats: 'Statistiken',
    finishActivity: 'Aktivität Beenden',
    pause: 'Pause',
    resume: 'Fortsetzen',
    currentSpeed: 'Aktuelle Geschwindigkeit',
    maxSpeed: 'Höchstgeschwindigkeit',
    route: 'Route',
  },
  it: {
    sportpi: 'SPORTPI',
    tagline: 'Guadagna Pi, Resta in Forma',
    home: 'Home',
    activities: 'Attività',
    challenges: 'Sfide',
    leaderboard: 'Classifica',
    profile: 'Profilo',
    piBalance: 'Saldo Pi',
    keepMoving: 'Continua a muoverti per guadagnare di più',
    todaySteps: 'Passi Oggi',
    goal: 'Obiettivo',
    recentActivities: 'Attività Recenti',
    exerciseRewards: 'Premi Esercizio',
    walking: 'Camminata',
    running: 'Corsa',
    cycling: 'Ciclismo',
    swimming: 'Nuoto',
    perKm: 'per km',
    today: 'Oggi',
    yesterday: 'Ieri',
    activeChallenge: 'Sfida Attiva',
    startActivity: 'Avvia Attività',
    stopActivity: 'Ferma Attività',
    elapsed: 'Tempo Trascorso',
    distance: 'Distanza',
    avgSpeed: 'Velocità Media',
    elevation: 'Elevazione',
    language: 'Lingua',
    selectLanguage: 'Seleziona Lingua',
    stats: 'Statistiche',
    finishActivity: 'Termina Attività',
    pause: 'Pausa',
    resume: 'Riprendi',
    currentSpeed: 'Velocità Attuale',
    maxSpeed: 'Velocità Massima',
    route: 'Percorso',
  },
  pt: {
    sportpi: 'SPORTPI',
    tagline: 'Ganhe Pi, Mantenha-se Fit',
    home: 'Início',
    activities: 'Atividades',
    challenges: 'Desafios',
    leaderboard: 'Placar',
    profile: 'Perfil',
    piBalance: 'Saldo de Pi',
    keepMoving: 'Continue se movendo para ganhar mais',
    todaySteps: 'Passos Hoje',
    goal: 'Meta',
    recentActivities: 'Atividades Recentes',
    exerciseRewards: 'Recompensas de Exercício',
    walking: 'Caminhada',
    running: 'Corrida',
    cycling: 'Ciclismo',
    swimming: 'Natação',
    perKm: 'por km',
    today: 'Hoje',
    yesterday: 'Ontem',
    activeChallenge: 'Desafio Ativo',
    startActivity: 'Iniciar Atividade',
    stopActivity: 'Parar Atividade',
    elapsed: 'Tempo Decorrido',
    distance: 'Distância',
    avgSpeed: 'Velocidade Média',
    elevation: 'Elevação',
    language: 'Idioma',
    selectLanguage: 'Selecionar Idioma',
    stats: 'Estatísticas',
    finishActivity: 'Terminar Atividade',
    pause: 'Pausa',
    resume: 'Retomar',
    currentSpeed: 'Velocidade Atual',
    maxSpeed: 'Velocidade Máxima',
    route: 'Rota',
  },
  ja: {
    sportpi: 'SPORTPI',
    tagline: 'Piを稼ぐ、フィットを保つ',
    home: 'ホーム',
    activities: 'アクティビティ',
    challenges: 'チャレンジ',
    leaderboard: 'リーダーボード',
    profile: 'プロフィール',
    piBalance: 'Pi残高',
    keepMoving: '動き続けてもっと稼ぐ',
    todaySteps: '今日のステップ',
    goal: '目標',
    recentActivities: '最近のアクティビティ',
    exerciseRewards: '運動報酬',
    walking: 'ウォーキング',
    running: 'ランニング',
    cycling: 'サイクリング',
    swimming: 'スイミング',
    perKm: '1km当たり',
    today: '今日',
    yesterday: '昨日',
    activeChallenge: 'アクティブなチャレンジ',
    startActivity: 'アクティビティを開始',
    stopActivity: 'アクティビティを停止',
    elapsed: '経過時間',
    distance: '距離',
    avgSpeed: '平均速度',
    elevation: '標高',
    language: '言語',
    selectLanguage: '言語を選択',
    stats: '統計',
    finishActivity: 'アクティビティを終了',
    pause: '一時停止',
    resume: '再開',
    currentSpeed: '現在の速度',
    maxSpeed: '最高速度',
    route: 'ルート',
  },
  ko: {
    sportpi: 'SPORTPI',
    tagline: 'Pi를 획득하고 건강하게 유지',
    home: '홈',
    activities: '활동',
    challenges: '챌린지',
    leaderboard: '순위표',
    profile: '프로필',
    piBalance: 'Pi 잔액',
    keepMoving: '계속 움직여서 더 많이 벌기',
    todaySteps: '오늘의 걸음',
    goal: '목표',
    recentActivities: '최근 활동',
    exerciseRewards: '운동 보상',
    walking: '산책',
    running: '달리기',
    cycling: '자전거',
    swimming: '수영',
    perKm: 'km당',
    today: '오늘',
    yesterday: '어제',
    activeChallenge: '활성 챌린지',
    startActivity: '활동 시작',
    stopActivity: '활동 중지',
    elapsed: '경과 시간',
    distance: '거리',
    avgSpeed: '평균 속도',
    elevation: '높이',
    language: '언어',
    selectLanguage: '언어 선택',
    stats: '통계',
    finishActivity: '활동 종료',
    pause: '일시 중지',
    resume: '재개',
    currentSpeed: '현재 속도',
    maxSpeed: '최고 속도',
    route: '경로',
  },
  zh: {
    sportpi: 'SPORTPI',
    tagline: '赚取Pi，保持健康',
    home: '首页',
    activities: '活动',
    challenges: '挑战',
    leaderboard: '排行榜',
    profile: '档案',
    piBalance: 'Pi余额',
    keepMoving: '继续运动以赚取更多',
    todaySteps: '今日步数',
    goal: '目标',
    recentActivities: '最近活动',
    exerciseRewards: '运动奖励',
    walking: '步行',
    running: '跑步',
    cycling: '骑行',
    swimming: '游泳',
    perKm: '每公里',
    today: '今天',
    yesterday: '昨天',
    activeChallenge: '活跃挑战',
    startActivity: '开始活动',
    stopActivity: '停止活动',
    elapsed: '经过时间',
    distance: '距离',
    avgSpeed: '平均速度',
    elevation: '海拔',
    language: '语言',
    selectLanguage: '选择语言',
    stats: '统计',
    finishActivity: '完成活动',
    pause: '暂停',
    resume: '继续',
    currentSpeed: '当前速度',
    maxSpeed: '最高速度',
    route: '路线',
  },
  ru: {
    sportpi: 'SPORTPI',
    tagline: 'Зарабатывайте Pi, оставайтесь в форме',
    home: 'Главная',
    activities: 'Активности',
    challenges: 'Вызовы',
    leaderboard: 'Таблица лидеров',
    profile: 'Профиль',
    piBalance: 'Баланс Pi',
    keepMoving: 'Продолжайте двигаться, чтобы заработать больше',
    todaySteps: 'Шаги сегодня',
    goal: 'Цель',
    recentActivities: 'Недавние активности',
    exerciseRewards: 'Награды за упражнения',
    walking: 'Ходьба',
    running: 'Бег',
    cycling: 'Езда на велосипеде',
    swimming: 'Плавание',
    perKm: 'за км',
    today: 'Сегодня',
    yesterday: 'Вчера',
    activeChallenge: 'Активный вызов',
    startActivity: 'Начать активность',
    stopActivity: 'Остановить активность',
    elapsed: 'Прошедшее время',
    distance: 'Расстояние',
    avgSpeed: 'Средняя скорость',
    elevation: 'Высота',
    language: 'Язык',
    selectLanguage: 'Выбрать язык',
    stats: 'Статистика',
    finishActivity: 'Завершить активность',
    pause: 'Пауза',
    resume: 'Возобновить',
    currentSpeed: 'Текущая скорость',
    maxSpeed: 'Максимальная скорость',
    route: 'Маршрут',
  },
  ar: {
    sportpi: 'SPORTPI',
    tagline: 'اكسب Pi ، ابق بصحة جيدة',
    home: 'الرئيسية',
    activities: 'الأنشطة',
    challenges: 'التحديات',
    leaderboard: 'لوحة الصدارة',
    profile: 'الملف الشخصي',
    piBalance: 'رصيد Pi',
    keepMoving: 'استمر في الحركة لكسب المزيد',
    todaySteps: 'خطوات اليوم',
    goal: 'الهدف',
    recentActivities: 'الأنشطة الحديثة',
    exerciseRewards: 'مكافآت التمرين',
    walking: 'المشي',
    running: 'الجري',
    cycling: 'ركوب الدراجات',
    swimming: 'السباحة',
    perKm: 'لكل كم',
    today: 'اليوم',
    yesterday: 'أمس',
    activeChallenge: 'تحدي نشط',
    startActivity: 'بدء النشاط',
    stopActivity: 'إيقاف النشاط',
    elapsed: 'الوقت المنقضي',
    distance: 'المسافة',
    avgSpeed: 'متوسط السرعة',
    elevation: 'الارتفاع',
    language: 'اللغة',
    selectLanguage: 'اختر اللغة',
    stats: 'الإحصائيات',
    finishActivity: 'إنهاء النشاط',
    pause: 'إيقاف مؤقت',
    resume: 'استئناف',
    currentSpeed: 'السرعة الحالية',
    maxSpeed: 'الحد الأقصى للسرعة',
    route: 'المسار',
  },
  hi: {
    sportpi: 'SPORTPI',
    tagline: 'Pi कमाएँ, फिट रहें',
    home: 'होम',
    activities: 'गतिविधियाँ',
    challenges: 'चुनौतियाँ',
    leaderboard: 'लीडरबोर्ड',
    profile: 'प्रोफाइल',
    piBalance: 'Pi बैलेंस',
    keepMoving: 'अधिक कमाने के लिए चलते रहें',
    todaySteps: 'आज की सीढ़ियाँ',
    goal: 'लक्ष्य',
    recentActivities: 'हाल की गतिविधियाँ',
    exerciseRewards: 'व्यायाम पुरस्कार',
    walking: 'चलना',
    running: 'दौड़ना',
    cycling: 'साइकिल चलाना',
    swimming: 'तैराकी',
    perKm: 'प्रति किमी',
    today: 'आज',
    yesterday: 'कल',
    activeChallenge: 'सक्रिय चुनौती',
    startActivity: 'गतिविधि शुरू करें',
    stopActivity: 'गतिविधि रोकें',
    elapsed: 'बीता हुआ समय',
    distance: 'दूरी',
    avgSpeed: 'औसत गति',
    elevation: 'ऊंचाई',
    language: 'भाषा',
    selectLanguage: 'भाषा चुनें',
    stats: 'आँकड़े',
    finishActivity: 'गतिविधि समाप्त करें',
    pause: 'रोकें',
    resume: 'फिर से शुरू करें',
    currentSpeed: 'वर्तमान गति',
    maxSpeed: 'अधिकतम गति',
    route: 'मार्ग',
  },
  tr: {
    sportpi: 'SPORTPI',
    tagline: 'Pi Kazan, Fit Kal',
    home: 'Anasayfa',
    activities: 'Aktiviteler',
    challenges: 'Zorluklar',
    leaderboard: 'Sıralama',
    profile: 'Profil',
    piBalance: 'Pi Bakiyesi',
    keepMoving: 'Daha fazla kazanmak için hareket etmeye devam edin',
    todaySteps: 'Bugün Adımlar',
    goal: 'Hedef',
    recentActivities: 'Son Aktiviteler',
    exerciseRewards: 'Egzersiz Ödülleri',
    walking: 'Yürüyüş',
    running: 'Koşu',
    cycling: 'Bisiklet',
    swimming: 'Yüzme',
    perKm: 'km başına',
    today: 'Bugün',
    yesterday: 'Dün',
    activeChallenge: 'Aktif Zorluk',
    startActivity: 'Aktiviteyi Başlat',
    stopActivity: 'Aktiviteyi Durdur',
    elapsed: 'Geçen Zaman',
    distance: 'Mesafe',
    avgSpeed: 'Ortalama Hız',
    elevation: 'Yükseklik',
    language: 'Dil',
    selectLanguage: 'Dil Seç',
    stats: 'İstatistikler',
    finishActivity: 'Aktiviteyi Bitir',
    pause: 'Duraklat',
    resume: 'Devam Et',
    currentSpeed: 'Mevcut Hız',
    maxSpeed: 'Maksimum Hız',
    route: 'Rota',
  },
  vi: {
    sportpi: 'SPORTPI',
    tagline: 'Kiếm Pi, Giữ Sức Khỏe',
    home: 'Trang Chủ',
    activities: 'Hoạt Động',
    challenges: 'Thách Thức',
    leaderboard: 'Bảng Xếp Hạng',
    profile: 'Hồ Sơ',
    piBalance: 'Số Dư Pi',
    keepMoving: 'Tiếp tục chuyển động để kiếm thêm',
    todaySteps: 'Bước Hôm Nay',
    goal: 'Mục Tiêu',
    recentActivities: 'Hoạt Động Gần Đây',
    exerciseRewards: 'Phần Thưởng Tập Luyện',
    walking: 'Đi Bộ',
    running: 'Chạy Bộ',
    cycling: 'Đi Xe Đạp',
    swimming: 'Bơi Lội',
    perKm: 'mỗi km',
    today: 'Hôm Nay',
    yesterday: 'Hôm Qua',
    activeChallenge: 'Thách Thức Hoạt Động',
    startActivity: 'Bắt Đầu Hoạt Động',
    stopActivity: 'Dừng Hoạt Động',
    elapsed: 'Thời Gian Đã Trôi Qua',
    distance: 'Khoảng Cách',
    avgSpeed: 'Tốc Độ Trung Bình',
    elevation: 'Độ Cao',
    language: 'Ngôn Ngữ',
    selectLanguage: 'Chọn Ngôn Ngữ',
    stats: 'Thống Kê',
    finishActivity: 'Kết Thúc Hoạt Động',
    pause: 'Tạm Dừng',
    resume: 'Tiếp Tục',
    currentSpeed: 'Tốc Độ Hiện Tại',
    maxSpeed: 'Tốc Độ Tối Đa',
    route: 'Tuyến Đường',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof (typeof translations)[Language]) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('es');

  const t = (key: keyof (typeof translations)[Language]): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}

const translations = {
  es: {
    sportpi: 'SPORTPI',
    tagline: 'Gana Pi, Mantente en Forma',
    home: 'Inicio',
    activities: 'Actividades',
    challenges: 'Retos',
    leaderboard: 'Ranking',
    profile: 'Perfil',
    piBalance: 'Saldo de Pi',
    keepMoving: 'Sigue moviendo para ganar más',
    todaySteps: 'Pasos de Hoy',
    goal: 'Objetivo',
    recentActivities: 'Actividades Recientes',
    exerciseRewards: 'Recompensas por Ejercicio',
    walking: 'Caminar',
    running: 'Correr',
    cycling: 'Ciclismo',
    swimming: 'Natación',
    perKm: 'por km',
    today: 'Hoy',
    yesterday: 'Ayer',
    activeChallenge: 'Reto Activo',
    startActivity: 'Iniciar Actividad',
    stopActivity: 'Detener Actividad',
    elapsed: 'Tiempo Transcurrido',
    distance: 'Distancia',
    avgSpeed: 'Velocidad Promedio',
    elevation: 'Elevación',
    language: 'Idioma',
    selectLanguage: 'Seleccionar Idioma',
    stats: 'Estadísticas',
    finishActivity: 'Finalizar Actividad',
    pause: 'Pausa',
    resume: 'Reanudar',
    currentSpeed: 'Velocidad Actual',
    maxSpeed: 'Velocidad Máxima',
    route: 'Ruta',
  },
  en: {
    sportpi: 'SPORTPI',
    tagline: 'Earn Pi, Stay Fit',
    home: 'Home',
    activities: 'Activities',
    challenges: 'Challenges',
    leaderboard: 'Leaderboard',
    profile: 'Profile',
    piBalance: 'Pi Balance',
    keepMoving: 'Keep moving to earn more',
    todaySteps: "Today's Steps",
    goal: 'Goal',
    recentActivities: 'Recent Activities',
    exerciseRewards: 'Exercise Rewards',
    walking: 'Walking',
    running: 'Running',
    cycling: 'Cycling',
    swimming: 'Swimming',
    perKm: 'per km',
    today: 'Today',
    yesterday: 'Yesterday',
    activeChallenge: 'Active Challenge',
    startActivity: 'Start Activity',
    stopActivity: 'Stop Activity',
    elapsed: 'Elapsed Time',
    distance: 'Distance',
    avgSpeed: 'Average Speed',
    elevation: 'Elevation',
    language: 'Language',
    selectLanguage: 'Select Language',
    stats: 'Stats',
    finishActivity: 'Finish Activity',
    pause: 'Pause',
    resume: 'Resume',
    currentSpeed: 'Current Speed',
    maxSpeed: 'Max Speed',
    route: 'Route',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof (typeof translations)[Language]) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('es');

  const t = (key: keyof (typeof translations)[Language]): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
